# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4fcb216260a84e76e5bb6cd83d1b57b47a50db574a44f8c932bb436e1b520eac2d9763d273e5354b55c4cf0525358d6d266e9efbe5b4b3c16427a3cde072bacc

test:
  secret_key_base: ba6ac21144ccfe69a3c2333bc05f4c7180500f4e116b7b36d482338e7a286a5ce60de454a746b27822d8f2fc3e4d17e4de6b32b5ae3cf63b4b5390c1f4eb1da0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
